name: Newsletter Workflow

on:
  schedule:
    - cron: '34 9 * * 2'  # Pour tester une exécution à 9h30 UTC tous les mardis
  workflow_dispatch:

jobs:
  run_newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the newsletter script
        run: python newsletter.py

