name: Newsletter Workflow

on:
  schedule:
    - cron: '28 9 * * 2'  # Exécutera le script chaque mardi à 10h25 (heure de Paris, UTC+1)
  workflow_dispatch:  # Permet de lancer manuellement le workflow si nécessaire

jobs:
  run_newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Spécifie la version de Python à utiliser

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances listées dans requirements.txt

      - name: Run the newsletter script
        run: python newsletter.py  # Lance ton script newsletter.py

